### PR TITLE
Trackstate

### PR DESCRIPTION
**Pull request by alicerobson**
Proposed new TrackState parameters (for discussion tomorrow). The parameters are based on LCIO track state parameters as detailed in http://www-flc.desy.de/lcnotes/notes/LC-DET-2006-004.pdf.
Alice

### CODE REVIEW

**Comment by cbernet** [comment]
I'd like to merge this as the current edm is anyway not functional (obviously missing information). If you have any objection could you please give us details?

**Comment by jlingema** [comment]
@jhrdinka could you have a look together with Andi if these parameters are in line with what you expect in ACTS?

**Comment by cgumpert** [comment]
Hi @jlingema,
one general note first: with ACTS we aim to support arbitrary track parametrisation schemes as there obviously is no _one-fits-all_ solution. In principle, this should not lead to many back-and-forth conversions since we foresee to use some template-magic for picking the right parametrisation. However, this is not implemented at the moment. While I am happy to add the implementation, this will need some time before it is available.

If you want to have something working ~now, I would recommend to stick to the current parametrisation we have in ACTS right now, which is: `loc0, loc1, phi, theta, q/p` and a reference surface. The reference surface + `(loc0,loc1)` give you the global coordinate (except for line-like surfaces like the perigee definition), `phi, theta` give you the momentum direction and `q/p` gives you the bending direction and the momentum.

Another note just for your information: the CPU intense task like track propagation use again their internal parametrisation (which is fixed inside ACTS, but you could provided specialised implementations there as well). For example, the Runge Kutta propagator uses the global position `(x,y,z)`, the normalized momentum vector `(Ax,Ay,Az)` and `q/p` internally. So when you call the ACTS track propagator there is **one** parameter transformation happening anyway.

**Comment by cbernet** [comment]
Hi Christian et al,

Thank you for the explanation.
I would agree with you I guess. 

But could you please provide a PR modifying edm.yaml and the definitions of all the variables you are mentioning? 

Cheers, 
Colin

**Comment by jlingema** [comment]
Re-posting a comment by Andi that he sent by email:

I would strongly advice against a helical track representations:

`cot(theta)/tan(theta)`, `pT` … are only constant of motion when you are in a perfect homogenous field

I would stick to the ACTS choice:

`theta`, `p`  

as a parameterisation, since this is basically field-agnostic.

Cheers,
Andi

**Comment by jlingema** [comment]
In case you did not notice, yet. Julia made an alternative proposal in PR #37

**Comment by jlingema** [comment]
This PR is superseded by #37, see discussion there.

**Pull request closed without merging**
