### PR TITLE
added MCEventWeight datatype

### PR DESCRIPTION
**Pull request by selvaggi**

### CODE REVIEW

**Comment by cbernet** [comment]
Hi Michele, all, 

I'd be fine with this, but I would be in favour of renaming this datatype as Float. 
In this way we could use it for many other things, and not only for MC event weights. 

But maybe native types are already defined by podio? @hegner 
and also arrays or native types?

Cheers!
C

**Comment by hegner** [comment]
I agree with @cbernet - just call it an fcc:float.

**Comment by selvaggi** [comment]
done.

**Comment by jlingema** [comment]
ok to test

**Pull request merged**
