### PR TITLE
Allow multiple tags for a tagged object

### PR DESCRIPTION
**Pull request by jlingema**
- (Re-)add `Tag`
- Change of `Tagged(Gen)Jet` and `TaggedParticle`:
  - Remove member `tag`
  - Add `OneToManyRelation` to `Tag`
- Add utility to find tags by collection name / id

### CODE REVIEW

**Comment by cbernet** [comment]
Hi Joschka, I reviewed the code and it looks good to me. We will need to update FCCSW and heppy accordingly, so that the Delphes example keeps working. @clementhelsens can you do that? Maybe Joschka should first merge this change in his edm branch (not sure, depends a bit on where we stand with the new version of root and the merge of the edm branch)

**Comment by jlingema** [comment]
Hi Colin, the branch is already merged in fcc-edm just not fcc-physics/heppy/FCCSW.

**Comment by jlingema** [comment]
Necessary changes for FCCSW Delphes are [here](https://github.com/jlingema/FCCSW/tree/edm)
I also installed the version corresponding to this PR in `/afs/cern.ch/exp/fcc/sw/snapshot/fcc-edm`

**Comment by jlingema** [comment]
As discussed, we'll go for another solution to this problem.

**Pull request closed without merging**
