### PR TITLE
Moving to PODIO and introducing namespace

### PR DESCRIPTION
**Pull request by jlingema**
With this PR we move to PODIO as the underlying library to generate the datamodel. Also, the whole EDM was moved to namespace `fcc`.

### CODE REVIEW

**Comment by cbernet** [comment]
Hi Joschka, 
Could you please confirm that the DummyGenerator is still used in fccedm-write? Is fccedm-read still reading what has been produced by the DummyGenerator? 
Thanks! 

Colin

**Comment by jlingema** [comment]
Hi Colin,
Yes, the DummyGenerator is used in fccedm-write (i.e. `examples/write.cc`) and the resulting root-file can be read with fccedm-read (i.e. `examples/read.cc`). Also worked for me on MacOS :-)
Cheers,
Joschka

**Comment by cbernet** [comment]
Hi Joschka, 

Thanks, sounds great.

I renamed HEP-FCC/albers into podio. 

Could you please PR your changes there as well? Btw I see 2 PRs pending in hegner/podio. Do you also have the code from @zaborowska in your github? 

Concerning integration, we have seen messages from the fcc-bot (nice!) but I guess we still have to do the testing manually this time. So what I'd like to do is to merge all your PRs to master in the respective packages. Then I would test the tutorials, make the needed modifications and merge master into tutorial. 

Cheers, 

Colin

**Comment by jlingema** [comment]
Hi Colin,

You probably saw that @hegner just did the PR / merge to HEP-FCC/podio. I think he didn't include the changes by @zaborowska, yet.

Indeed we'll have to do the integration by hand for now. However, I'll add fcc-edm and podio to our Jenkins nightlies later today. Also, I just added the read/write examples as test targets in my last commits.

Cheers,
Joschka

**Pull request merged**
