### PR TITLE
fix multicore compilation

### PR DESCRIPTION
**Pull request by cbernet**
Hi guys, 

This fixes the multicore compilation in fcc-edm. 

@jlingema I see that the cmake files for podio and fcc-edm have diverged. Any reason for that? do you intend to modify the cmake files in fcc-edm as in podio? 

This is really a naive question, I don't know enough of CMake to understand what you're doing in the podio cmake files. If you can add comments in these files at some point when you have time, I'd be interested in taking a look and learn a bit :-)

Cheers!

Colin

### CODE REVIEW

**Comment by cbernet** [comment]
This does not seem to solve the problem on lxplus. 
However, the single core compilation  works so I'd still recommend merging.

```
[ 99%] Built target datamodel-dictgen
Error: Cannot find datamodel.cxx_tmp!
Error: Renaming datamodel.cxx_tmp into datamodel.cxx!
make[2]: *** [datamodel/datamodel.cxx] Error 1
make[1]: *** [datamodel/CMakeFiles/datamodelDict.dir/all] Error 2
make: *** [all] Error 2
```

The only difference I see is that I'm using root 6.04.06 on lxplus and 6.04.08 on the mac. investigating...

**Comment by jlingema** [comment]
Hi Colin,

regarding the cmake-files, I actually only did small changes, they were simplified by Benedikt and Pere. In any case, the idea is to similarly simplify the fcc-edm cmake files, yes. I can also add some more comments in PODIO.

Cheers,
Joschka

**Comment by cbernet** [comment]
about the datamodel target name: I have not modified it and it's not related to this PR. Moreover I think it involves mods in other packages, so I would prefer not to do it now.

**Comment by hegner** [comment]
@cbernet: you did rename. from ExampleDict to datamodel. ;-)

**Comment by hegner** [comment]
@cbernet - regarding the CMake files. The idea is to simplify fcc-edm as well. Let's discuss technical questions via email then. I guess you mean the ones in cmake/ and not the main one which got documentation.

**Comment by cbernet** [comment]
Actually, I renamed ExampleDict to datamodelDict.
We don’t care about this guy, it’s here to handle dependencies afaiu. 
it’s the libary containing the dictionary for the datamodel target. 

I did not rename the datamodel target that is used in downstream packages.

**Comment by hegner** [comment]
@cbernet - indeed. Then we put it onto the long-term list. So from my side the PR looks OK, the bot agrees as well.

**Comment by cbernet** [comment]
Shouldn't the bot have picked up the problem mentioned here?  
https://github.com/HEP-FCC/fcc-edm/pull/7#issuecomment-181747525

**Comment by hegner** [comment]
@cbernet - it is compiling single threaded right now. We need to fix the race condition indeed.

**Pull request merged**
