### PR TITLE
Dev tagging - new edm_1.2.yaml implementing the tagging info to the FCC-EDM

### PR DESCRIPTION
**Pull request by drasal**
Created new version of edm configuration file: edm_1.2.yaml implementing the Tagging info and (gen)jet<->tag relations

Comments:
- Colin proposed to use TagFloat and TagBool container and relations between Jet(GenJet) and Tag information
  - TagBool was supposed to be used for tagging algorithms providing true/false
  - TagFloat was supposed to be used for tagging algorithms providing info in <-1;+1> interval, i.e. +1/-1 (e.g quark/antiQuark) times tagging quality (0,1)
  - Each jet than contains relations to tag results from various jet algorithms
- As the relations in the simple POD structure would need to be duplicated Jet(GenJet)<->TagFloat and Jet(GenJet)<->TagBool, I have implemented just the TagFloat, called Tag for now and relations Jet<->Tag & GenJet<->Tag
- Once one can define relations with Base class Tag and use derived classes TagFloat, TagBool, we might implement both options, currently float covers both: float & bool

### CODE REVIEW

**Comment by drasal** [comment]
To admins: if you prefer having different scheme of tagging, please, let me know and I will update the current change.

**Comment by cbernet** [comment]
Hi Zbynek, 

Please implement the change in edm_1.yaml  and remove edm_1.2.yaml, 
so that we can keep track of modifications. 
I will rename the yaml file _later_ to edm.yaml

To keep track of edm versions, we can use a git tag. 

Thanks, 

Colin

**Comment by drasal** [comment]
@cbernet Done!

**Comment by cbernet** [comment]
retest this please

**Comment by cbernet** [comment]
@jlingema @hegner looks like testing has not been done on this PR, and is not being started by my latest comment. Would you have any idea of what's going on?

**Comment by hegner** [comment]
@cbernet - in the meantime it has started. There is a delay of a few mins. Zbynek's commit didn't start it automatically because zbynek is not part of the HEP-FCC github team. And here we restricted auto-testing properly. Thats why the bot asked...  we need to apply the same rules for the other projects as well.

**Pull request merged**
